apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Namespace }}-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  MONGODB_URI: |
    {{ tpl (printf "mongodb://%s:%s@%s:%d/%s?authSource=admin" 
      .Values.mongo.root.user 
      .Values.mongo.root.password 
      .Values.mongo.service.name 
      ( .Values.mongo.service.port | int ) 
      .Values.mongo.databaseName | quote ) . }}
