image:
  name: zoo-backend
  tag: "latest"
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: false
  hostTemplate: "api-zoo-{{ .Release.Namespace }}.example.com"
mongo:
  service:
    name: "zoo-mongo-{{ .Release.Namespace }}-svc"
    port: 27017
  root:
    user: ""     # From cmd line
    password: "" # From cmd line
  databaseName: "zoo"

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
